version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install awscli
          command: pip install awscli --user

      - run:
          name: Install SAM
          command: pip install aws-sam-cli==0.39 --user

      - run:
          name: Deploy with SAM
          command: |
            # export PYTHONPATH=/home/xy/caffe-master/python:$PYTHONPATH
            which pip
            python -c "import sys; print(sys.path)"
            python -c "import pip; print(pip.__version__)"

            sam build --debug
            sam deploy --template-file ./template.yaml --stack-name journal --s3-bucket emshea-journal --region us-east-1 --capabilities CAPABILITY_IAM

            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #   sam deploy --template-file ./packaged-template.yaml --stack-name basic-stack --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides Param1=param1-override Stage=prod
            # fi
            # if [ "${CIRCLE_BRANCH}" == "staging" ]; then
            #   sam deploy --template-file ./packaged-template.yaml --stack-name basic-stack-staging --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides Param1=param1-override-staging Stage=staging
            # fi
